[package]
name = "arb_transfer"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "2.0", features = ["rustls", "ws"] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"      # 可选，加载 .env 文件
hex = "0.4"
anyhow = "1.0"