[package]
name = "arbi_eth_send"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "2", features = ["rustls"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde_json = "1"
